### ISSUE TITLE
fatal: Couldn't find remote ref

### ISSUE THREAD

**Issue by shijianjian** [saadmk11/changelog-ci#38]
I am running into an issue with the git checkout.
```
Checkout git repository
  fatal: Couldn't find remote ref changelog
  error: pathspec 'changelog' did not match any file(s) known to git
```
Which is triggered by:
https://github.com/saadmk11/changelog-ci/blob/73b906e9060f5fbfa4112bccc114ed59fba076f4/scripts/changelog-ci.py#L555-L559

May I ask why do we need to checkout if we have ```actions/checkout@v2``` already?

**Comment by saadmk11** [comment]
Can you please share a little bit more about the repository you are running this on?
such as the repository is public or private (if public it would be great if you could share the output page for the action) :)

**Comment by shijianjian** [comment]
Thank you. After some research, I found that the changelog can only be generated by the repo owner. But not from the forked repo.

It runs well after created a dev branch in the repo itself.

**Comment by saadmk11** [comment]
Great :100: , I'm planning to add this feature in the future, need to think about the security concerns, and see what GitHub has for this.

**Comment by shijianjian** [comment]
It is not pretty doable I think. I cannot find the link but github APIs are not supporting this. You will only have read access to main repo issues. Good luck with this!

Also, one potential feature may be to disable the generation of "other changes". So the not labelled PRs will not be included in the changelog.

**Comment by saadmk11** [comment]
closing in favor of https://github.com/saadmk11/changelog-ci/issues/41 and https://github.com/saadmk11/changelog-ci/issues/42
