### ISSUE TITLE
Generate changelog for forked repo PR

### ISSUE THREAD

**Issue by saadmk11** [saadmk11/changelog-ci#41]
Currently, changelog-ci does not support committing changelog from a fork repo PR because of permission issues. More research is needed on this issue.

ref: https://github.com/saadmk11/changelog-ci/issues/38

**Comment by saadmk11** [comment]
GitHub added some settings for this on `https://github.com/<username>/<repo>/settings/actions` page

**Comment by robinmatz** [comment]
Hi @saadmk11 , I am facing this issue on Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library, see e.g. [this failed job](https://github.com/Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library/actions/runs/4523976438).

What settings are you referring to specifically? I tried the URL you mentioned with one of my personal project, but I don't seem to find anything useful.
