### ISSUE TITLE
[Question] How version matching is working?  Could not find matching version number. Regex tried: v?([0-9]{1,2})+[.]+([0-9]{1,2})+[.]+([0-9]{1,2})\s\(\d{1,2}-\d{1,2}-\d{4}\) Aborting Changelog Generation

### ISSUE THREAD

**Issue by MikeVaz** [saadmk11/changelog-ci#44]
I am trying with pull request now which seems to work but I am getting an error

```
Could not find matching version number. Regex tried: v?([0-9]{1,2})+[.]+([0-9]{1,2})+[.]+([0-9]{1,2})\s\(\d{1,2}-\d{1,2}-\d{4}\) Aborting Changelog Generation
```

Could explain where it is looking for versions?

**Comment by saadmk11** [comment]
This regex is looking for the version number in the pull request title.

You can see an example of the default regex here:  
https://regex101.com/r/RT4zK7/1

You can also read the documentation for more information and examples of the config file.:
Docs: https://github.com/saadmk11/changelog-ci/blob/c27fe4cab5bf37ec4ed34ba00f0aedb65cfe5687/README.md#example-config-file

Example pull request: https://github.com/saadmk11/changelog-ci/pull/36

**Comment by MikeVaz** [comment]
You have 

```
In this Example version_regex matches any version number including date. e.g: v1.1.0 (01-23-2018) If you don't provide any regex Changelog CI will use default SemVer pattern. e.g. 1.0.1, v1.0.2.
```

It would be nice to clarify that

```markup
In this Example version_regex matches any version number *in the pull request title* including date. e.g: v1.1.0 (01-23-2018) If you don't provide any regex Changelog CI will use default SemVer pattern. e.g. 1.0.1, v1.0.2.
```
