### ISSUE TITLE
The commit history is replicated in each version generated with each new PR

### ISSUE THREAD

**Issue by BlindadoXp** [saadmk11/changelog-ci#80]
## Describe the bug

Every time I create a new PR it shows me the first commit by default that was created when the repository was started and all the commits associated with previous PRs (It doesn't show those of the PR that I am managing at the moment)

## Your Environment

Repo: https://github.com/BlindadoXp/testch
Every step that I did in case you can guide me because I am confusing the process

**Step 1:**
```
- git checkout -b branch_1
- Create empty [CHANGELOG.md](https://github.com/saadmk11/changelog-ci/blob/v1.0.0/CHANGELOG.md)
- Create changelog-ci-config.json
- Create changelog-ci.yml (remove workflow_dispatch and replace changelog_filename with ./CHANGELOG.md If I don't do this, it returns me the message that the changelog is not found. Remove committer_username and  committer_email)
- Git add -A & git commit -m “First commit” & git push branch_1
- Create pr Release/v1.0.0 (03-16-2022)
- Merge PR & delete branch in GitHub
```

**FIRST PR:** 
Changelog: Version: v1.0.0 (03-16-2022)
* [e4a3277] Initial commit (It is not my commit, it is the first one that was created by default when the repository was created)

**Step 2:**
```
- git checkout main & git pull & delete branch local 
- git checkout -b branch_2
- Create folder api + api/fastapi.py
- git add -A
- git commit -m "Create api/fastapi.py"
- git push origin branch_2
- Add # into api/fastapi.py
- git add -A
- git commit -m "Add # into api/fastapi.py"
- git push origin branch_2
- Create a new pr Release/v2.0.0 (03-16-2022)
- Merge PR & delete branch in GitHub
```

**SECOND PR:** 
Version: v2.0.0 (03-16-2022)
* [faa2fc9] [Changelog CI] Add Changelog for Version v1.0.0 (03-16-2022)
* [941665a]First commit
* [e4a3277] Initial commit 

The second changelog was created with the commits of the previous PR and also added the first commit by default that was created when generating the repository

**Step 3:**
```
- git checkout main & git pull & delete branch local 
- git checkout -b branch_3
- Add another # into api/fastapi.py
- git add -A
-  git commit -m "Add another # into api/fastapi.py"
- git push origin branch_3
- Create new pr Release/v3.0.0 (03-16-2022)
- Merge PR & delete branch in GitHub
```

**THIRD PR:** 
Version: v3.0.0 (03-16-2022)
* [dfbdd56] [Changelog CI] Add Changelog for Version v2.0.0 (03-16-2022)
* [966d486] Add # into api/fastapi.py
* [d62b3af]Create api/fastapi.py
* [faa2fc9][Changelog CI] Add Changelog for Version v1.0.0 (03-16-2022)
* [941665a]First commit
* [e4a3277] Initial commit

It is a mix of the first commit by default, the commits of the first PR and the second

**Comment by saadmk11** [comment]
Please refer to this issue: https://github.com/saadmk11/changelog-ci/issues/78
