### ISSUE TITLE
custom path for CHANGELOG.md?

### ISSUE THREAD

**Issue by nihartsx** [saadmk11/changelog-ci#82]
I'd like to be able to provide a custom path for CHANGELOG.md. Is it possible currently?

**Comment by saadmk11** [comment]
I think you can use the `changelog_filename` input option to specify a file name with a different path. 

e.g. `changelog_filename: docs/CHANGELOG.rst`

More details on inputs can be found here: https://github.com/saadmk11/changelog-ci#workflow-input-options

**Comment by nihartsx** [comment]
Thank you @saadmk11
