### ISSUE TITLE
Fail v1.1.1 RUN pip install -r requirements.txt PyYAML~=5.4.1 Deprecated config in `setup.cfg`

### ISSUE THREAD

**Issue by juanspinelli** [saadmk11/changelog-ci#99]
## Describe the bug
Step fail when starting running pip install.

![image](https://github.com/saadmk11/changelog-ci/assets/47563834/8a990706-be0a-4db3-bbde-31427268cde1)

**Comment by saadmk11** [comment]
Fixed in: https://github.com/saadmk11/changelog-ci/pull/100

**Comment by bushong1** [comment]
@saadmk11 can we get a release that includes this bugfix?

**Comment by saadmk11** [comment]
> @saadmk11 can we get a release that includes this bugfix?

I am planning on releasing the changes this weekend.

**Comment by saadmk11** [comment]
Released [`v1.1.2`](https://github.com/saadmk11/changelog-ci/releases/tag/v1.1.2). The issue should be fixed now. Feel free to re-open the issue if the problem still exists.
